modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/squeek502/AppleSkin"
license="The Unlicense"

[[mods]]
modId="appleskin"
version="${file.jarVersion}"
displayName="AppleSkin"
#updateJSONURL=""
displayURL="https://github.com/squeek502/AppleSkin"
logoFile="appleskin.png"
authors="squeek"
description="Adds various food-related HUD improvements"

[[dependencies.appleskin]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.12,)"
    ordering="AFTER"
    side="CLIENT"